name: Merge development branch to main branch

on: [workflow_dispatch]

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.email "bot@mazanec.dev"
          git config user.name "Bot"

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: npm ci

      - name: Check for changesets
        run: npx changeset status --since=origin/main

      - name: Checkout development branch
        run: |
          git fetch -p origin
          git checkout development
          git branch --set-upstream-to=origin/development development
          git reset --hard origin/development
          git pull

      - name: Checkout main branch
        run: |
          git checkout -B main
          git branch --set-upstream-to=origin/main main
          git reset --hard origin/main

      - name: Merge and commit
        run: |
          git merge development --no-verify
          git push -u origin main --no-verify

      - name: Trigger release
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/jakubmazanec/js-tools/actions/workflows/release.yaml/dispatches \
            -d '{"ref": "main"}'
